### PR TITLE
Count extended fingers & build path modification

### PR DESCRIPTION
**Pull request by nathanshelly**
Hi,

I've been using your patch for a school project and have found it incredibly valuable, thank you so much for making it! If you're interested here are two commits that I think would make using the patch a slightly nicer experience. The two are completely unconnected and can be cherry picked if you would like one but not the other (assuming you want either at all). A little more detail on each commit:

1. `Count extended fingers only` - currently the `numfingers` value output by the patch is always as many fingers as one has on their hand (for me always five, don't have any friends with less fingers to test with 😄 ). I needed to count the number of extended fingers in the course of my project so I added `extended()` to the patch to do so (apologies if you're aware of this and purposely wanted total number of fingers vs extended).
2. `Generate target in repo root` - changes the target path to generate the patch at the root of the repo. This one is definitely opinionated, I found it slightly confusing that the build process generated a target outside the repo and in a max5 folder. I think generating it to the root might be a little more clear to users what they've generated.

Thanks again for making such a helpful tool! Please let me know if there's anything you'd like from me to help this pull request go through!

### CODE REVIEW

**Comment by nathanshelly** [comment]
Closing since you haven't expressed any interest in this, if at a later point you'd like to implement these would love to talk then!

**Comment by JulesFrancoise** [comment]
Hi @nathanshelly 

My apologies, I didn't get a chance to look into it yet!
I reopened the PR to keep it in mind and will try to have a look.

Thanks!
Jules

**Comment by nathanshelly** [comment]
No worries whatsoever! Just figured I wouldn't leave an open ended PR if you were busy with other things 😃. If you get a chance to have a look and have any questions please let me know!

**Comment by JulesFrancoise** [comment]
It looks straightforward so I merged your PR.
I will add a new release when I get my hand on a leap motion (I don't have one at the moment).
Thanks for your contribution!

**Pull request merged**
